// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTaTMCCPfdqPe_2eCnJmnNWwf32ghEvEY',
    appId: '1:23598205527:web:abb0f3f35a60c4a5573112',
    messagingSenderId: '23598205527',
    projectId: 'navus-8a033',
    authDomain: 'navus-8a033.firebaseapp.com',
    storageBucket: 'navus-8a033.appspot.com',
    measurementId: 'G-80Y7NBQGVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvVmfBDSFh-KQSYCNiE85n6xBUA3ROYM',
    appId: '1:23598205527:android:95125def15c7e02e573112',
    messagingSenderId: '23598205527',
    projectId: 'navus-8a033',
    storageBucket: 'navus-8a033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLlA5YfAboWv3fACZ_hU_ZW6jlIjNOCVE',
    appId: '1:23598205527:ios:9b32d79040b695f0573112',
    messagingSenderId: '23598205527',
    projectId: 'navus-8a033',
    storageBucket: 'navus-8a033.appspot.com',
    iosClientId: '23598205527-jsf72n9t997e76ksmovufgt31k0l4m0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.progress1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLlA5YfAboWv3fACZ_hU_ZW6jlIjNOCVE',
    appId: '1:23598205527:ios:9b32d79040b695f0573112',
    messagingSenderId: '23598205527',
    projectId: 'navus-8a033',
    storageBucket: 'navus-8a033.appspot.com',
    iosClientId: '23598205527-jsf72n9t997e76ksmovufgt31k0l4m0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.progress1',
  );
}
